name:                Huffman-Compression
version:             0.1.0.0
github:              "O-Zone-Guy/Huffman-Compression"
license:             BSD3
author:              "Omar"
maintainer:          "oalkersh@ymail.com"
copyright:           "Omar @2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            EXPERIMENTAL

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/O-Zone-Guy/Huffman-Compression#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Huffman-Compression-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman-Compression

tests:
  Huffman-Compression-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman-Compression
